name:                aoc2021
version:             0.1.0.0
github:              "FourCredits/aoc2021"
license:             BSD3
author:              "Erik Grundy"
maintainer:          "erik.grundy@gmail.com"
copyright:           "2021 Erik Grundy"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            "The 2021 Advent of Code in Haskell"
category:            Recreational

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc2021#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- parsec
- array
- mtl

library:
  source-dirs: src

executables:
  aoc2021-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021

tests:
  aoc2021-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021
    - HUnit
